services:
  micro-discovery-service:
    build:  ./discovery-service
    container_name: micro-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
  micro-config-service:
    build: ./config-service
    container_name: micro-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://micro-discovery-service:8761/eureka
    depends_on:
        micro-discovery-service:
          condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
  micro-customer-service:
    build: ./customer-service
    container_name: micro-customer-service
    ports:
      - '8089:8089'
    expose:
      - '8089'
    depends_on:
      micro-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8089/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://micro-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://micro-config-service:9999
  micro-inventory-service:
      build: ./inventory-service
      container_name: micro-inventory-service
      ports:
        - '8082:8082'
      expose:
        - '8082'
      depends_on:
        micro-config-service:
          condition: service_healthy
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      environment:
        - DISCOVERY_SERVICE_URL=http://micro-discovery-service:8761/eureka
        - CONFIG_SERVER_URL=http://micro-config-service:9999
  micro-billing-service:
    build: ./billing-service
    container_name: micro-billing-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    depends_on:
      micro-config-service:
        condition: service_healthy
      micro-inventory-service:
        condition: service_healthy
      micro-customer-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://micro-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://micro-config-service:9999
  gatewey-inventory-service:
    build: ./gatewey-service
    container_name: micro-gatewey-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      micro-config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://micro-discovery-service:8761/eureka
      - CONFIG_SERVER_URL=http://micro-config-service:9999

































